### ISSUE TITLE
Error: The size of bytes exceeds the length of whole bytes.

### ISSUE THREAD

**Issue by zcbenz** [nonzzz/tar#5]
Passing a stream to createExtract results in the error.

```
/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:584
            throw new Error(FAST_BYTES_ERROR_MESSAGES.EXCEED_BYTES_LEN);
            ^

Error: The size of bytes exceeds the length of whole bytes.
    at FastBytes.peek (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:584:19)
    at Extract.transport (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:713:35)
    at Writable.write [as _write] (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:754:22)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Gunzip.ondata (node:internal/streams/readable:1007:22)
    at Gunzip.emit (node:events:520:28)
    at Gunzip.emit (node:domain:488:12)
    at addChunk (node:internal/streams/readable:559:12)
```

```typescript
import {Readable} from 'node:stream';
import {finished} from 'node:stream/promises';
import {createGunzip} from 'node:zlib';
import {fileURLToPath} from 'node:url';

import * as tar from 'tar-mini';

export async function untar(url: string, targetDir: string) {
  // Fetch url.
  const response = await fetch(url);
  if (!response.ok || !response.body)
    throw new Error(`fetch failed with status code: ${response.status}`);
  let readable = Readable.fromWeb(response.body);
  // Handle gzip decompression.
  if (url.endsWith('.gz') || url.endsWith('.tgz')) {
    readable = readable.pipe(createGunzip());
  }
  // Parse the files.
  const extract = tar.createExtract();
  extract.on('entry', (head, file) => {
  });
  await finished(readable.pipe(extract.receiver));
}

untar('https://nodejs.org/dist/v22.7.0/node-v22.7.0-headers.tar.gz', '/tmp/headers');
```

**Comment by nonzzz** [comment]
This is a stupid mistake. I removed the binary by mistake. A release will be soon.

**Comment by nonzzz** [comment]
Done!

**Comment by zcbenz** [comment]
It seems that I can still get this error, it happens much less now but if you change the url to something else like https://nodejs.org/dist/v22.7.0/node-v22.7.0-darwin-x64.tar.gz the error could still happen occasionally:

```
/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:563
            throw new Error(FAST_BYTES_ERROR_MESSAGES.EXCEED_BYTES_LEN);
            ^

Error: The size of bytes exceeds the length of whole bytes.
    at FastBytes.shift (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:563:19)
    at Extract.removePadding (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:608:25)
    at Extract.transport (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:708:38)
    at Writable.write [as _write] (/Users/zcbenz/codes/untar-url/node_modules/tar-mini/dist/index.js:771:22)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Gunzip.ondata (node:internal/streams/readable:1007:22)
    at Gunzip.emit (node:events:520:28)
    at Gunzip.emit (node:domain:488:12)
```

**Comment by nonzzz** [comment]
seems like web stream pipe to node stream cause the occur. I'll check it.

**Comment by zcbenz** [comment]
Another stack trace:

```
/home/runner/work/untar-url/untar-url/node_modules/tar-mini/dist/index.js:563
            throw new Error(FAST_BYTES_ERROR_MESSAGES.EXCEED_BYTES_LEN);
            ^

Error: The size of bytes exceeds the length of whole bytes.
    at FastBytes.shift (/home/runner/work/untar-url/untar-url/node_modules/tar-mini/dist/index.js:563:19)
    at handleLongPath (/home/runner/work/untar-url/untar-url/node_modules/tar-mini/dist/index.js:673:35)
    at handleNonUSTARFormat (/home/runner/work/untar-url/untar-url/node_modules/tar-mini/dist/index.js:693:21)
    at Extract.transport (/home/runner/work/untar-url/untar-url/node_modules/tar-mini/dist/index.js:700:17)
    at Writable.write [as _write] (/home/runner/work/untar-url/untar-url/node_modules/tar-mini/dist/index.js:771:22)
    at writeOrBuffer (node:internal/streams/writable:570:12)
    at _write (node:internal/streams/writable:499:10)
    at Writable.write (node:internal/streams/writable:508:10)
    at Gunzip.ondata (node:internal/streams/readable:1007:22)
    at Gunzip.emit (node:events:520:28)
```

**Comment by nonzzz** [comment]
I create a new release.

**Comment by zcbenz** [comment]
It works perfectly, thanks for working on this!

I'm using this package in https://github.com/compilets/untar-url and https://github.com/compilets/compilets.
